import { BadgeCheck, Clock, Coins, LogOut, ShieldCheck } from "lucide-react";
import { useEffect, useState } from "react";
import { api, formatPlayTime } from "../lib/api";
import type { MeResponse } from "../lib/types";

export function AccountPage() {
  const [me, setMe] = useState<MeResponse | null>(null);
  const [error, setError] = useState("");
  useEffect(() => { api.me().then(setMe).catch(err => setError(err.message)); }, []);
  if (error) return <div className="page section narrow"><div className="empty-state"><h1>Portal unavailable</h1><p>{error}</p></div></div>;
  if (!me) return <div className="page section narrow"><div className="loading-card"><i /><span>Finding your trainer…</span></div></div>;
  if (!me.authenticated) return <div className="page section account-intro"><div><span className="eyebrow">Trainer portal</span><h1>Your adventure,<br />at a glance.</h1><p>Sign in with the same Discord identity you use in PokePlanet. Website sign-in never launches, changes, or controls your game session.</p><a className="button button-discord" href="/api/auth/discord/start"><svg viewBox="0 0 24 24" aria-hidden="true"><path fill="currentColor" d="M19.5 5.3A16 16 0 0 0 15.6 4l-.5 1a14 14 0 0 0-6.2 0l-.5-1a16 16 0 0 0-3.9 1.3C2 9 1.3 12.6 1.6 16.2a16 16 0 0 0 4.8 2.4l1.2-1.7-1.9-.9.5-.4c3.7 1.7 7.8 1.7 11.5 0l.6.4-2 .9 1.2 1.7a16 16 0 0 0 4.8-2.4c.4-4.1-.7-7.7-2.8-10.9ZM8.7 14.3c-1.1 0-2-1-2-2.2s.9-2.2 2-2.2 2 1 2 2.2-.9 2.2-2 2.2Zm6.6 0c-1.1 0-2-1-2-2.2s.9-2.2 2-2.2 2 1 2 2.2-.9 2.2-2 2.2Z"/></svg>Continue with Discord</a><small className="privacy-note"><ShieldCheck size={15} />We request only your basic Discord identity.</small></div><div className="portal-preview"><div className="preview-head"><i /><span>TRAINER PROFILE</span></div><div className="preview-avatar">?</div><div className="preview-lines"><i /><i /><i /></div></div></div>;
  const trainer = me.character;
  return <div className="page section account-page"><div className="account-bar"><div><img src={me.user?.avatar_url} alt="" /><span><small>Signed in as</small><b>{me.user?.display_name}</b></span></div><button className="button button-small button-ghost" onClick={() => api.logout().then(() => location.reload())}><LogOut size={15} />Sign out</button></div>{trainer ? <><div className="trainer-hero"><div className="trainer-avatar"><span>{trainer.name.slice(0, 1).toUpperCase()}</span><small>Sprite #{trainer.graphics_id}</small></div><div><span className="eyebrow">Welcome back</span><h1>{trainer.name}</h1><p>Last seen near {trainer.location}</p></div></div><div className="stats-grid"><article><Clock /><small>Play time</small><b>{formatPlayTime(trainer.play_time_seconds)}</b></article><article><BadgeCheck /><small>Badges</small><b>{trainer.badges} / 8</b></article><article><span className="stat-icon">◉</span><small>Pokédex</small><b>{trainer.pokedex_caught} caught</b></article><article><Coins /><small>Pokédollars</small><b>₽ {trainer.money.toLocaleString()}</b></article></div><section className="party-panel"><span className="eyebrow">Current party</span><div>{trainer.party.length ? trainer.party.map((mon, index) => <article key={`${mon.species}-${index}`}><span>{String(mon.species).padStart(3, "0")}</span><b>{mon.name}</b><small>Lv. {mon.level}</small></article>) : <p className="muted">Your party appears after the next successful server save.</p>}</div></section></> : <div className="empty-state"><h2>No trainer found yet</h2><p>Launch PokePlanet and complete game sign-in once. Your server-side character will then appear here automatically.</p><a className="button" href="/download">Download PokePlanet</a></div>}</div>;
}

