import { ArrowRight, Download, Github, Play, Sparkles } from "lucide-react";
import { Link } from "react-router-dom";
import { StatusPill } from "../components/StatusPill";
import { DISCORD_URL, features, GAMEPLAY_VIDEO_URL, GAME_SOURCE_URL } from "../lib/content";

export function Home() {
  return <>
    <section className="hero section"><div className="hero-copy"><StatusPill /><div className="hero-kicker"><Sparkles size={15} /> A new kind of Emerald adventure</div><h1>One world.<br /><em>Every trainer.</em></h1><p className="hero-lead">PokePlanet turns Pokémon Emerald into a living, server-authoritative MMORPG. Explore Hoenn, meet trainers, battle, chat, and keep your journey wherever you play.</p><div className="button-row"><Link className="button button-large" to="/download"><Download size={19} />Download alpha</Link><a className="button button-large button-ghost" href={DISCORD_URL} target="_blank" rel="noreferrer">Join Discord<ArrowRight size={18} /></a></div><div className="hero-notes"><span>Free & open source</span><span>No pay-to-win</span><span>Discord sign-in</span></div></div>
      <div className="hero-visual"><div className="planet"><div className="planet-grid" /><div className="planet-core"><span>HOENN</span><b>ONLINE</b></div><div className="moon moon-one" /><div className="moon moon-two" /></div><div className="trainer-card trainer-a"><span className="sprite sprite-green">◆</span><div><b>Trainer nearby</b><small>Littleroot Town</small></div></div><div className="trainer-card trainer-b"><span className="sprite sprite-blue">●</span><div><b>Battle ready</b><small>2 trainers connected</small></div></div></div>
    </section>
    <section className="section proof-strip"><div><b>60</b><span>frames per second</span></div><div><b>79+</b><span>server tests</span></div><div><b>3</b><span>chat scopes</span></div><div><b>0</b><span>pay-to-win mechanics</span></div></section>
    <section className="section"><div className="section-heading"><span className="eyebrow">Emerald, connected</span><h2>The game you remember.<br />A world you have not seen.</h2><p>Authentic at its core, rebuilt around real people and a server that protects every adventure.</p></div><div className="feature-grid">{features.map(({ icon: Icon, title, text }, index) => <article className="feature-card" key={title}><span className="feature-number">0{index + 1}</span><Icon /><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section className="section showcase"><div className="showcase-copy"><span className="eyebrow">See it running</span><h2>Hoenn feels different when someone else is there.</h2><p>Two independent accounts, one shared world. Movement, identity, saves, and battles travel through a purpose-built Rust network stack.</p><Link to="/media" className="text-link">Explore the gallery <ArrowRight size={16} /></Link></div><div className="video-frame"><video src={GAMEPLAY_VIDEO_URL} poster="/media/world-presence.webp" controls preload="metadata" aria-label="Two PokePlanet clients moving in the same world" /><span className="video-label"><Play size={14} /> Real gameplay capture</span></div></section>
    <section className="section open-source"><div><Github size={32} /><span className="eyebrow">Built in public</span><h2>Read every line.<br />Help shape the planet.</h2></div><div><p>The game, server, network protocol, roadmap, and website are open. Follow development, report bugs, or build your own client.</p><a className="button button-ghost" href={GAME_SOURCE_URL} target="_blank" rel="noreferrer">Explore the source <ArrowRight size={17} /></a></div></section>
  </>;
}
