import { ArrowRight, Download, Github, Play, Skull } from "lucide-react";
import { Link } from "react-router-dom";
import { StatusPill } from "../components/StatusPill";
import { deadmanPillars, DISCORD_URL, features, GAMEPLAY_VIDEO_URL, GAME_SOURCE_URL } from "../lib/content";

export function Home() {
  return <>
    <section className="hero section"><div className="hero-copy"><StatusPill /><div className="hero-kicker"><Skull size={15} /> Pokémon Emerald, made deadly</div><h1>Death is<br /><em>permanent.</em></h1><p className="hero-lead">PokePlanet Deadman turns Pokémon Emerald into a server-authoritative, permadeath MMORPG. A fainted Pokémon dies forever. Progress is capped to your next gym, captures are scarce and hard-won, and everything you carry is on the line. No local saves, nothing to undo — the server is the only authority.</p><div className="button-row"><Link className="button button-large" to="/download"><Download size={19} />Download alpha</Link><a className="button button-large button-ghost" href={DISCORD_URL} target="_blank" rel="noreferrer">Join Discord<ArrowRight size={18} /></a></div><div className="hero-notes"><span>Permadeath</span><span>No pay-to-win</span><span>Impossible to cheat</span></div></div>
      <div className="hero-visual"><div className="planet"><div className="planet-grid" /><div className="planet-core"><span>HOENN</span><b>DEADMAN</b></div><div className="moon moon-one" /><div className="moon moon-two" /></div><div className="trainer-card trainer-a"><span className="sprite sprite-green">◆</span><div><b>Trainer nearby</b><small>Within striking distance</small></div></div><div className="trainer-card trainer-b"><span className="sprite sprite-blue">✝</span><div><b>A run just ended</b><small>Everything lost</small></div></div></div>
    </section>
    <section className="section proof-strip"><div><b>∞</b><span>ways to lose it all</span></div><div><b>0.8×</b><span>experience rate</span></div><div><b>1</b><span>life per run</span></div><div><b>0</b><span>pay-to-win mechanics</span></div></section>
    <section className="section"><div className="section-heading"><span className="eyebrow">The Deadman rules</span><h2>Every choice is final.<br />That is the whole point.</h2><p>Deadman strips out the safety net. Plan ahead, weigh every fight, and earn a run you can be proud of — or watch it end in an instant.</p></div><div className="feature-grid deadman-pillars">{deadmanPillars.map(({ icon: Icon, title, text }, index) => <article className="feature-card" key={title}><span className="feature-number">0{index + 1}</span><Icon /><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section className="section showcase"><div className="showcase-copy"><span className="eyebrow">See it running</span><h2>Hoenn is far more tense when a wrong step is forever.</h2><p>Two independent accounts, one shared and unforgiving world. Movement, identity, saves, deaths, and battles travel through a purpose-built Rust network stack that no client can lie to.</p><Link to="/media" className="text-link">Explore the gallery <ArrowRight size={16} /></Link></div><div className="video-frame"><video src={GAMEPLAY_VIDEO_URL} poster="/media/world-presence.webp" controls preload="metadata" aria-label="Two PokePlanet clients moving in the same world" /><span className="video-label"><Play size={14} /> Real gameplay capture</span></div></section>
    <section className="section"><div className="section-heading"><span className="eyebrow">Under the hood</span><h2>Built to be brutal, and fair.</h2><p>The stakes only mean something because none of it can be faked. Every asset that moves is validated on the server.</p></div><div className="feature-grid">{features.map(({ icon: Icon, title, text }, index) => <article className="feature-card" key={title}><span className="feature-number">0{index + 1}</span><Icon /><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section className="section standard-note"><div><span className="eyebrow">Not ready to die?</span><h2>There is a standard world too.</h2><p>PokePlanet also runs a classic, non-permadeath world — the same shared Hoenn, without the stakes. Pick your world when you sign in.</p></div><Link className="button button-ghost" to="/about">How the worlds differ <ArrowRight size={17} /></Link></section>
    <section className="section open-source"><div><Github size={32} /><span className="eyebrow">Built in public</span><h2>Read every line.<br />Help shape the planet.</h2></div><div><p>The game, server, network protocol, roadmap, and website are open. Follow development, report bugs, or build your own client.</p><a className="button button-ghost" href={GAME_SOURCE_URL} target="_blank" rel="noreferrer">Explore the source <ArrowRight size={17} /></a></div></section>
  </>;
}
